# Generated by Django 6.0.3 on 2026-06-17 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='hospital_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='hospital_name',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
