# Generated by Django 6.0.3 on 2026-06-24 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0003_doctor_blood_group_doctor_dob_doctor_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='experience',
            field=models.PositiveIntegerField(default=0, help_text='Years of experience'),
        ),
    ]
