# Generated by Django 6.0.3 on 2026-06-18 04:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0003_doctor_blood_group_doctor_dob_doctor_gender'),
        ('healthstatus', '0001_initial'),
        ('patients', '0003_patient_blood_group_patient_dob_patient_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthstatus',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_records', to='doctors.doctor'),
        ),
        migrations.AlterField(
            model_name='healthstatus',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_records', to='patients.patient'),
        ),
    ]
