# Generated by Django 6.0.3 on 2026-06-16 13:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0001_initial'),
        ('patients', '0001_initial'),
        ('prescriptions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prescription',
            old_name='details',
            new_name='medicine',
        ),
        migrations.AddField(
            model_name='prescription',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='doctors.doctor'),
        ),
        migrations.AddField(
            model_name='prescription',
            name='dosage',
            field=models.CharField(default='Not specified', max_length=100),
        ),
        migrations.AddField(
            model_name='prescription',
            name='instructions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.patient'),
        ),
    ]
