# Generated by Django 6.0.3 on 2026-06-17 06:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctors', '0003_doctor_blood_group_doctor_dob_doctor_gender'),
        ('patients', '0003_patient_blood_group_patient_dob_patient_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_date', models.DateTimeField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('doctor_cancelled', 'Doctor Cancelled'), ('patient_cancelled', 'Patient Cancelled')], default='pending', max_length=20)),
                ('reason', models.TextField(blank=True, null=True)),
                ('doctor_deleted', models.BooleanField(default=False)),
                ('patient_deleted', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='doctors.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='patients.patient')),
            ],
            options={
                'ordering': ['-appointment_date'],
            },
        ),
    ]
